// Public landing page stays outside the authenticated workspace shell.
import Link from "next/link";
import { ArrowRight, CheckCircle2, Link2, ListChecks, Users } from "lucide-react";

const features = [[ListChecks, "Create & assign", "Bring clarity to every task."], [Users, "Track progress", "See real work, not placeholder metrics."], [Link2, "Respect dependencies", "Blocked work stays visible until ready."]] as const;

export default function Home() {
  return <main>
    <header className="mx-auto flex max-w-6xl items-center justify-between px-4 py-4 sm:px-5 sm:py-5"><Link href="/" className="flex items-center gap-2 text-sm font-bold sm:text-base"><span className="grid size-8 place-items-center rounded-xl bg-indigo-600 text-white sm:size-9"><CheckCircle2 size={18} /></span>Smart Tasks</Link><div className="flex gap-2 sm:gap-3"><Link className="btn btn-secondary px-3 py-2 text-xs sm:text-sm" href="/login">Sign in</Link><Link className="btn btn-primary px-3 py-2 text-xs sm:px-4 sm:text-sm" href="/login">Get started <ArrowRight size={15} /></Link></div></header>
    <section className="mx-auto grid max-w-6xl items-center gap-8 px-4 py-12 sm:gap-12 sm:px-5 sm:py-16 md:grid-cols-2 md:py-28"><div><p className="inline rounded-full bg-indigo-50 px-3 py-1 text-[10px] font-bold tracking-wider text-indigo-600 sm:text-xs">SMART TASK MANAGEMENT</p><h1 className="mt-4 text-3xl font-extrabold tracking-tight text-[#102047] sm:mt-5 sm:text-5xl lg:text-6xl">Plan work. Track progress.<br /><span className="text-indigo-500">Get things done.</span></h1><p className="mt-4 max-w-lg text-sm leading-6 text-slate-500 sm:mt-6 sm:text-lg sm:leading-8">A focused workspace to create tasks, assign owners, and keep dependent work moving in the right order.</p><div className="mt-6 flex flex-wrap gap-3 sm:mt-8"><Link href="/login" className="btn btn-primary">Get started <ArrowRight size={16} /></Link><Link href="/login" className="btn btn-secondary">Sign in</Link></div></div><div className="card overflow-hidden bg-gradient-to-br from-slate-50 to-indigo-50 p-3 sm:p-5"><div className="rounded-xl bg-[#102047] p-4 text-white"><p className="text-sm font-bold sm:text-base">Smart Tasks</p><div className="mt-4 grid grid-cols-3 gap-2 sm:mt-5 sm:gap-3">{["To Do", "In Progress", "Done"].map((item, index) => <div key={item} className="rounded-lg bg-white/10 p-2 sm:p-3"><p className="text-[10px] text-indigo-100 sm:text-xs">{item}</p><p className="mt-1 text-xl font-bold sm:mt-2 sm:text-2xl">{index + 1}</p></div>)}</div></div><div className="mt-3 space-y-2 sm:mt-4 sm:space-y-3">{["Create clear tasks", "Assign the right owner", "Respect dependencies"].map((item) => <div key={item} className="rounded-xl bg-white p-3 text-xs font-semibold shadow-sm sm:p-4 sm:text-sm">{item}</div>)}</div></div></section>
    <section className="border-y border-slate-200 bg-white px-4 py-12 sm:px-5 sm:py-16"><h2 className="text-center text-lg font-bold sm:text-2xl">Everything you need to keep work moving.</h2><div className="mx-auto mt-8 grid max-w-5xl gap-8 md:mt-10 md:grid-cols-3">{features.map(([Icon, title, copy]) => <div className="text-center" key={title}><span className="mx-auto grid size-11 place-items-center rounded-2xl bg-indigo-50 text-indigo-600 sm:size-12"><Icon size={20} /></span><h3 className="mt-4 text-sm font-bold sm:text-base">{title}</h3><p className="mt-2 text-xs text-slate-500 sm:text-sm">{copy}</p></div>)}</div></section>
    <footer className="px-5 py-7 text-center text-xs text-slate-500">© {new Date().getFullYear()} Smart Tasks · Plan work. Make progress.</footer>
  </main>;
}
